### ISSUE TITLE
The source link is broken.

### ISSUE THREAD

**Issue by AcckiyGerman** [datasets/oil-prices#2]
https://www.eia.gov/dnav/pet/hist_xls/RBRTE  is not working.
http://www.eia.gov/dnav/pet/hist_xls/RWTC is not working

## tasks

* [ ] find new sources
* [ ] update script

**Comment by anuveyatsu** [comment]
Source links mentioned in the issue's description are incorrect. Please, read the script file to construct the full URLs that work.
